- README.md
What
---
updated badges on readme
Why
---
> docs: updated badges on readme

- .github/workflows/release.yml
- .release-it.json
- package-lock.json
- package.json
What
---
removed release-it package.json versioning
Why
---
> chore: removed release-it package.json versioning

- README.md
- docs/index.md
- docs/typescript.md
- package-lock.json
- package.json
What
---
updated package name to @belvo/payments-atoms
Why
---
> chore: updated package name to @belvo/payments-atoms

- .release-it.json
- README.md
- package-lock.json
- package.json
What
---
updated package json and readme
Why
---
> chore: updated package json and readme

- README.md
- docs/index.md
- package.json
What
---
update npm badge height on readme
Why
---
> chore: update npm badge height on readme

- .release-it.json
What
---
set conventional changelog infile to undefined
Why
---
> chore: set conventional changelog infile to undefined

- .release-it.json
What
---
set changelog config to release-it.json
Why
---
> chore: set changelog config to release-it.json

- .release-it.json
What
---
update changelog preset to conventionalcommits
Why
---
> chore: update changelog preset to conventionalcommits

- .release-it.json
What
---
add types to conventional changelog
Why
---
> chore: add types to conventional changelog

- .github/workflows/release.yml
What
---
Removing global GitHub credentials.
> fix: removing global github credentials

- .github/workflows/release.yml
Reverts belvo-finance-opensource/payments-atoms#73
> Revert "fix: removing global github credentials"

- package.json
What
---
Bumping to 0.0.30 to match NPM.
> fix: bumping to 0.0.30 to match NPM

- .github/workflows/release.yml
- .release-it.json
- package-lock.json
- package.json
What
---
NPM version out of sync issue fixed.
> fix: npm version out of sync issue fixed

- .github/workflows/deploy-to-gh-pages.yml
- examples/next-js/app/page.tsx
- examples/next-js/next.config.mjs
- examples/next-js/package-lock.json
- examples/next-js/package.json
- examples/react/package-lock.json
- examples/react/package.json
What
---
added examples to gh pages
Why
---
> chore: added examples to gh pages

- examples/next-js/next.config.mjs
- examples/react/package.json
What
---
Fixed examples base path issue
Why
---
> fix: examples base path issue

- README.md
- docs/index.md
- examples/next-js/app/page.tsx
- examples/react/src/App.js
What
---
added examples to docs
Why
---
> docs: added examples to docs

- .github/workflows/deploy-to-gh-pages.yml
- README.md
- docs/index.md
- examples/next-js/next.config.mjs
- examples/react/package.json
What
---
Changed examples route
Why
---
> chore: changed examples route

- README.md
What
---
Adding docs status badge into `Readme.md`
> docs: adding docs status badge into readme

- src/services/pix/BelvoPaymentsAtomsPix.ts
- src/services/pix/belvoPaymentsAtomsPix.spec.ts
- src/types/pix.ts
What
---
Biometric PIX signals added
> feat: biometric PIX signals added

- src/services/pix/BelvoPaymentsAtomsPix.ts
- src/services/pix/belvoPaymentsAtomsPix.spec.ts
- src/types/pix.ts
> feat: Biometric PIX login

- vite.config.ts
What
---
chore: setting new coverage thresholds
Why
---
> chore: setting new coverage thresholds

- package-lock.json
- package.json
What
---
fix: downgrading conventional changelog plugin to avoid issues with releases
> fix: downgrading conventional changelog plugin to avoid issues with releases

- src/services/pix/BelvoPaymentsAtomsPix.ts
- src/services/pix/belvoPaymentsAtomsPix.spec.ts
- src/types/pix.ts
What
---
account tenure validation and timezone zero pad added
> chore: account tenure validation and timezone zero pad added

- examples/next-js/package-lock.json
- examples/next-js/package.json
- examples/react/package-lock.json
- examples/react/package.json
What
---
dependencies update
Why
---
> chore: dependencies update

- src/services/pix/BelvoPaymentsAtomsPix.ts
- src/services/pix/belvoPaymentsAtomsPix.spec.ts
- src/types/pix.ts
Reverts belvo-finance-opensource/payments-atoms#395
> chore: revert converting response payloads to snake case

- package-lock.json
- package.json
- pix.yaml
- src/components/main.spec.ts
- src/components/main.ts
- src/services/pix/BelvoPaymentsAtomsPix.ts
- src/services/pix/belvoPaymentsAtomsPix.spec.ts
- src/types/pix.ts
What
---
fix: fixing response shape
> fix: fixing response shape

- package.json
- schemas/open-api/pix.yaml
- src/types/pix.ts
What
---
chore: adding schema folder
> chore: adding schema folder

- schemas/open-api/pix.yaml
- src/types/pix.ts
What
---
fix: adding missing register optional options
> fix: adding missing register optional options

- src/services/pix/BelvoPaymentsAtomsPix.ts
- src/services/pix/belvoPaymentsAtomsPix.spec.ts
- src/types/pix.ts
fix: fixing biometric PIX registration response
> fix: fixing biometric PIX registration response

- src/services/pix/BelvoPaymentsAtomsPix.ts
fix: fix register payload response id encode
> fix: fix register payload response id encode

- src/services/pix/BelvoPaymentsAtomsPix.ts
- src/services/pix/belvoPaymentsAtomsPix.spec.ts
fix: lanague field set to 2 chars
> fix: lanague field set to 2 chars

- src/services/pix/BelvoPaymentsAtomsPix.ts
- src/services/pix/belvoPaymentsAtomsPix.spec.ts
fix: challenge and user.id base64 requirement removed
> fix: challenge and user.id base64 requirement removed

- src/services/pix/BelvoPaymentsAtomsPix.ts
- src/services/pix/belvoPaymentsAtomsPix.spec.ts
remove base64 conversion from biometric pix fields
> fix: remove base64 conversion from biometric pix fields

- src/services/pix/BelvoPaymentsAtomsPix.ts
- src/services/pix/belvoPaymentsAtomsPix.spec.ts
> fix: decode challenge

- examples/biometricPix/playground/src/App.vue
chore: playground responses as textarea
> chore: playground responses as textarea

- src/services/pix/BelvoPaymentsAtomsPix.ts
- src/services/pix/belvoPaymentsAtomsPix.spec.ts
> fix: remove challenge encode

- src/services/pix/BelvoPaymentsAtomsPix.ts
- src/services/pix/belvoPaymentsAtomsPix.spec.ts
> fix: remove id encoding

- examples/biometricPix/playground/src/App.vue
- examples/biometricPix/playground/src/assets/base.css
What
---
- Organize CSS files and styling rules.
- Fix JSON formatting feature.
- Make the User ID a randomly generated string to avoid duplicated credential registration.
- Make the challenge a randomly generated base64url string to simulate a real environment without need for extra developer input.
- Improve WebAuthn default parameters to show all the available options to the developer.
> chore: organize and clean up CSS and fido inputs

- examples/biometricPix/playground/README.md
What
---
- Fix all linting warnings
> chore: fix README markdown warnings

- .github/workflows/deploy-to-gh-pages.yml
chore: add biometric pix playground on GH pages
> chore: add biometric pix playground on GH pages

- .github/workflows/deploy-to-gh-pages.yml
fix: fix pix playground GH pages
> fix: fix pix playground GH pages

- .github/workflows/deploy-to-gh-pages.yml
- examples/biometricPix/playground/package-lock.json
- examples/biometricPix/playground/package.json
fix: playground deploy to GH pages
> fix: playground deploy to GH pages

- .github/workflows/deploy-to-gh-pages.yml
fix: fix biometric pix gh page deploy
> fix: fix biometric pix gh page deploy

- examples/biometricPix/playground/package.json
chore: payment atoms as latest version and readme update
> chore: payment atoms as latest version and readme update

- src/services/pix/BelvoPaymentsAtomsPix.ts
fix: credential id encoder removed
> fix: credential id encoder removed

- src/services/pix/BelvoPaymentsAtomsPix.ts
fix: remove allowed credentials parser
> fix: remove allowed credentials parser

- package-lock.json
What
---
- Fix dependency sync in the package-lock.json file.
> fix: sync npm lock file

- package-lock.json
- src/components/main.spec.ts
- src/components/main.ts
- src/services/pix/BelvoPaymentsAtomsPix.ts
[What
---
Why
---
](feat: export webauthn availability check)
> feat: export webauthn availability check

- src/services/pix/BelvoPaymentsAtomsPix.ts
What
---
update FingenprintJS to use belvo's subdomain endpoint
> feat: update FingenprintJS to use belvo's subdomain endpoint

- src/services/pix/BelvoPaymentsAtomsPix.ts
What
---
- Log original biometric error so we can properly debug
> chore: log original biometric error for debugging
